### ISSUE TITLE
Update dosn't work

### ISSUE THREAD

**Issue by kraeml** [hassio-addons/addon-jupyterlab#239]
# Problem/Motivation

Message from jupyterlab addon:
You are running Home Assistant 2021.2.2, to install this add-on you need at least version of Home Assistant 

## Expected behavior

In the newest version of Home Assistant the update to jupyterlab 0.4 should possible.

## Actual behavior

Update not possible

## Steps to reproduce

Update available! 🎉

JupyterLab Lite 0.4.0 is available
You are currently running version 0.3.1

You are running Home Assistant 2021.2.2, to update to this version of the add-on you need at least version of Home Assistant

**Comment by Luc3as** [comment]
I uninstalled the addon and installed again, it worked.

**Comment by kraeml** [comment]
Ups, I uninstalled jupyterlab-lite. But these message is comming up

```
This add-on is not compatible with the processor of your device or the operating system you have installed on your device. 
```
## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.10.11-v7+
arch | armv7l
timezone | Europe/Berlin

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4969
Installed Version | 1.9.0
Stage | running
Available Repositories | 747
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Raspbian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.9
docker_version | 20.10.3
disk_total | 29.0 GB
disk_used | 13.5 GB
healthy | true
supported | failed to load: Unsupported
supervisor_api | ok
version_api | ok
installed_addons | Glances (0.11.0), ESPHome (1.16.1), Check Home Assistant configuration (3.6.0), Node-RED (8.1.1), Grafana (6.1.1), Mosquitto broker (5.1), Portainer (1.4.0), Terminal & SSH (9.0.1), JupyterLab Lite (0.3.1), File editor (5.2.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 0
views | 4
mode | storage

</details>

Why is the plugin jupyter-lab with 0.3.1 installed? I uninstalled it.

Thx Kraeml

**Comment by frenck** [comment]
See release notes:

<https://github.com/hassio-addons/addon-jupyterlab/releases/tag/v0.4.0>

`Support for armhf/armv7 has been dropped.`

The error message is correct.

**Comment by kraeml** [comment]
What is the problem with armhf/armv7? The integration of Jupyter in Homeassistant was great for me. One of the reasons to change from OpenHab was the integration from nodered, jupyter and RaspberryPi. Is there more information or could I help?

Thx Kraeml

**Comment by frenck** [comment]
The dependencies aren't adding up. If there is one generally big issue in the data science community; it is supporting other architectures. I've spent many days getting it built (the average build cycle is a couple of hours), but there simply isn't a combination of packages that allows for shipping this add-on.

The situation hasn't improved in months either, so in order to be able to continue releasing and maintaining this add-on, I had no choice.

Please notes, that a Raspberry Pi 3B+ and newer is already capable of running aarch64 (64 bits arms), for which the add-on is available (if a 64-bits OS is used).
