### ISSUE TITLE
Problem with View States section in Getting Started : 'HassDatabase' object has no attribute 'fetch_all_data'

### ISSUE THREAD

**Issue by dmshimself** [hassio-addons/addon-jupyterlab#241]
# Problem/Motivation

I've run the addon up against HA 2021.2.3 and which also uses the mariadb addon.  The initial connection works fine and displays 

There are 188 entities with data

The Popular enties works fine as does next up, but View States shows:

db.fetch_all_data()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

AttributeError: 'HassDatabase' object has no attribute 'fetch_all_data'

## Expected behavior

The statement should return all the data from the mariab DB.

## Actual behavior

db.fetch_all_data()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed eval> in <module>

AttributeError: 'HassDatabase' object has no attribute 'fetch_all_data'

## Steps to reproduce

Install hassos 2012.1.3
Install and configure add on mariadb
Install jupyterlab addon, configure token and run add on

**Comment by frenck** [comment]
Hi there @dmshimself!

This is provided by the package called `HASS-data-detective`, this project can be found here:

<https://github.com/robmarkcole/HASS-data-detective>

See: <https://github.com/robmarkcole/HASS-data-detective/blob/master/detective/core.py#L38>

Please report the issue upstream. Once it is fixed, the add-on will be updated as well.

Sorry that I'm not able to provide a more satisfying answer.

../Frenck

**Comment by dmshimself** [comment]
Many thanks indeed!

**Comment by dmshimself** [comment]
Hi Frank - would you mind looking at

https://github.com/robmarkcole/HASS-data-detective/issues/137#issuecomment-781848825

as it appears there might be a mismatch between Robs work and the HA add-on?
