### ISSUE TITLE
JupyterLab Lite in Supervisor not updating to 0.5.0

### ISSUE THREAD

**Issue by magicmatt007** [hassio-addons/addon-jupyterlab#263]
# Problem/Motivation
HASSIO supervisor shows the following message (I'm using a Raspberry PI3B):

Update pending🎉
JupyterLab Lite 0.5.0 is available
You are currently running version 0.3.1
**This add-on is not compatible with the processor of your device or the operating system you have installed on your device.**
I'd like to updated to the latest version 0.5.0

## Expected behavior
Being able to update. No error message regarding operating system

## Actual behavior
Update not possible.

## Steps to reproduce
Maybe use a Raspberry PI3B ?

## Proposed changes

**Comment by frenck** [comment]
See release notes:

![image](https://user-images.githubusercontent.com/195327/116544492-81026500-a8ef-11eb-8f19-8ee5f3b1a8ee.png)


<https://github.com/hassio-addons/addon-jupyterlab/releases/tag/v0.4.0>

**Comment by magicmatt007** [comment]
Thanks for the quick reply.
Hm, too bad......
I thought that a lot of people use hassio on a Raspberry PI....

**Comment by frenck** [comment]
Yes they do
