### ISSUE TITLE
Error 502 when opening web-interface

### ISSUE THREAD

**Issue by michael5411** [hassio-addons/addon-jupyterlab#322]
# Problem/Motivation
> Did use the addon for about 12 months, but it was lost after an update.

## Actual behavior
> with any click on "open web interface" I get an error 502.

## Steps to reproduce
> Cleared cache - no change
> Delete - new install - no change

I think, there is nothing that one can do wrong by using the addon-installation? 
Just install and start. there is no config needed to get the addon startet.

So seems to be a real bug?

**Comment by tjorim** [comment]
Probably duplicate of https://github.com/hassio-addons/addon-jupyterlab/issues/319.
Please provide logs and check them.

**Comment by frenck** [comment]
Fixed in https://github.com/hassio-addons/addon-jupyterlab/releases/tag/v0.8.2
