### ISSUE TITLE
Getting Started Notebook fails on first run

### ISSUE THREAD

**Issue by chicagoandy** [hassio-addons/addon-jupyterlab#425]
# Problem/Motivation

After completing a fresh install of the plugin, I tried using the getting-started notebook.   It failed on step 3 of the notebook:

import detective.core as detective
import detective.functions as functions
import pandas as pd
​
db = detective.db_from_hass_config()
YAML tag !include_dir_merge_named is not supported
Successfully connected to database sqlite:////config/home-assistant_v2.db
Error with query: 
            SELECT DISTINCT(entity_id) FROM states
            
'Engine' object has no attribute 'execute'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 5
      2 import detective.functions as functions
      3 import pandas as pd
----> 5 db = detective.db_from_hass_config()

File /usr/local/lib/python3.9/dist-packages/detective/core.py:19, in db_from_hass_config(path, **kwargs)
     16     path = config.find_hass_config()
     18 url = config.db_url_from_hass_config(path)
---> 19 return HassDatabase(url, **kwargs)

File /usr/local/lib/python3.9/dist-packages/detective/core.py:57, in HassDatabase.__init__(self, url, fetch_entities)
     55     print("Successfully connected to database", stripped_db_url(url))
     56     if fetch_entities:
---> 57         self.fetch_entities()
     58 except Exception as exc:
     59     if isinstance(exc, ImportError):

File /usr/local/lib/python3.9/dist-packages/detective/core.py:85, in HassDatabase.fetch_entities(self)
     79 """Fetch entities for which we have data."""
     80 query = text(
     81     """
     82     SELECT DISTINCT(entity_id) FROM states
     83     """
     84 )
---> 85 response = self.perform_query(query)
     87 # Parse the domains from the entities.
     88 self.entities = [e[0] for e in response]

File /usr/local/lib/python3.9/dist-packages/detective/core.py:73, in HassDatabase.perform_query(self, query, **params)
     71 """Perform a query."""
     72 try:
---> 73     return self.engine.execute(query, params)
     74 except:
     75     print(f"Error with query: {query}")

AttributeError: 'Engine' object has no attribute 'execute'

**Comment by frenck** [comment]
The database format is changed quite a bit over the past releases, additionally, the Home Assistant project now uses SQLAlchemey 2.x, it seems like the `detective` package  and notebooks by Home Assistant haven't adjusted to these changes yet.

Please report these issues upstream, once they update, the add-on will update as well.

../Frenck
