### ISSUE TITLE
Example "GETTING STARTED.ipynb" is broken

### ISSUE THREAD

**Issue by bjornvanraaij** [hassio-addons/addon-jupyterlab#491]
# Problem/Motivation

> Since the update to SQLAlchemy 2.0 the GETTING STARTED tutorial/example stopped working

## Expected behavior

> The example (and database query) should execute to show the reader how Jupyter might work

## Actual behavior

> Running all cells results in an error (ObjectNotExecutableError  Traceback (most recent call last) Cell In[12], line 13)

## Steps to reproduce

> Just run the the code as told in the example

## Proposed changes

> It seems that 'raw strings' are not permitted anymore in SQLAlchemy 2.0, the add-on has recently been updated so this example doesn't work anymore. Using the sqlalchemy text function (per example https://stackoverflow.com/questions/69490450/objectnotexecutableerror-when-executing-any-sql-query-using-asyncengine) solves the issue for me: 

for event in db.perform_query(**text(**"SELECT * FROM events WHERE event_type = 'call_service' ORDER BY time_fired"**)**):

**Comment by frenck** [comment]
The example provided is not maintained by the add-on, but provided by the Home Assistant project. Please report the issue upstream. Once their case is fixed, the add-on will pick it up automatically.

../Frenck

**Comment by bjornvanraaij** [comment]
Thx. Sorry, just getting the hang of this.

KR

Bjørn
