### ISSUE TITLE
Support of jupyter scheduler

### ISSUE THREAD

**Issue by Lars-Heinen** [hassio-addons/addon-jupyterlab#503]
# Problem/Motivation

Schedule a job for frequent repetition of a prediction function located inside a notebook.

## Expected behavior

"pip install jupyter_scheduler" runs through installation process and extension is usable in Jupiter lab add-on.

## Actual behavior

Installation routin stops with the following error:

      Failed to build psutil
      copying psutil/tests/test_aix.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_osx.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/__main__.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_memleaks.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_connections.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_bsd.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_contracts.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_process.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_sunos.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      copying psutil/tests/test_misc.py -> build/lib.linux-aarch64-cpython-311/psutil/tests
      warning: build_py: byte-compiling is disabled, skipping.
      
      running build_ext
      building 'psutil._psutil_linux' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/psutil
      aarch64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=595 -DPy_LIMITED_API=0x03060000 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -DPSUTIL_LINUX=1 -I/usr/include/python3.11 -c psutil/_psutil_common.c -o build/temp.linux-aarch64-cpython-311/psutil/_psutil_common.o
      psutil could not be installed from sources because gcc is not installed. Try running:
        sudo apt-get install gcc python3-dev
      error: command 'aarch64-linux-gnu-gcc' failed: No such file or directory
      [end of output]

## Steps to reproduce

Placed pip install command in the configuration part of the add-on. Restart the add-on.
```

Version
Add-on: JupyterLab
 Create documents containing live code, equations, visualizations, and explanatory text
-----------------------------------------------------------
 Add-on version: 0.12.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.9.2
 Home Assistant Supervisor: 2023.09.2
```

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by sinclairpaul** [comment]
I can't duplicate

```
github_access_token: ""
system_packages: []
init_commands:
  - pip install jupyter_scheduler 
````
Can you post your config?

![image](https://github.com/hassio-addons/addon-jupyterlab/assets/24625998/14f40468-eb83-4c29-b6db-65dc716eb7d3)

**Comment by Lars-Heinen** [comment]
I tried it with both notations: same result = psutil error.
version is: jupyterlab v4.0.4
This is the add-on configuration:
![image](https://github.com/hassio-addons/addon-jupyterlab/assets/76663802/49549c21-3603-457a-bea0-e75498b0a5c5)

I am using the following HA version:
![image](https://github.com/hassio-addons/addon-jupyterlab/assets/76663802/d6fa47db-239c-4f28-a3ca-26e7682b98fa)

Running on an raspi 64-4 booting from external SSD.

Does this answer your question regarding the config?

Attached also the snapshot of the protokoll during startup.

![image](https://github.com/hassio-addons/addon-jupyterlab/assets/76663802/c6e08136-4c24-401e-9dda-551febc2169a)



Thx for the fast support.

**Comment by sinclairpaul** [comment]
Maybe it's an arch issue, you can try adding gcc and python3-dev to the system packages config.

**Comment by Lars-Heinen** [comment]
Works!
![image](https://github.com/hassio-addons/addon-jupyterlab/assets/76663802/4860de58-a3cf-47d1-87fa-57525e9abb1f)
Thx a lot!
