### ISSUE TITLE
Feature Request: Add PyScript Jupyter kernel or provide instructions

### ISSUE THREAD

**Issue by rct** [hassio-addons/addon-jupyterlab#635]
# Problem/Motivation

Adding the [PyScript](https://github.com/custom-components/pyscript) Jupyter Kernel [craigbarratt/hass-pyscript-jupyter](https://github.com/craigbarratt/hass-pyscript-jupyter) would make this add-on more useful out of the box for accessing and exploring your data in Home Assistant. 

From https://github.com/custom-components/pyscript/issues/317 the benefits for PyScript users would be:

*  I don't have to setup a python environment and jupyter on my personal computer
*  I don't have to setup a long-lived access token
*  it works from anywhere
*  it shows up inside the Home Assistant UI

## Expected behavior

> (What you expected to happen)

Either have the PyScript kernel pre-installed, or have [some easy to follow instructions](https://github.com/custom-components/pyscript/issues/317) for getting running with PyScript.

Ideally the PyScript kernel would get the Home Assistant connection details (hostname, access token) from the add-on, making it easy to get up and running.

**Comment by rct** [comment]
I should also add that many Windows/macOS users wind up installing the Anaconda Python/Jupyter distribution on their desktop/laptops.  Doing `pip installs` in the conda environment (and mixing package managers in the same environment) can be problematic. 

See https://github.com/craigbarratt/hass-pyscript-jupyter/issues/31

**Comment by frenck** [comment]
I currently have no plans to add this kernel.

But you are free to run extra command to install anything into this environment. See:

https://github.com/hassio-addons/addon-jupyterlab/blob/main/jupyterlab/DOCS.md#option-init_commands

Nevertheless, thanks for the suggestion 👍 

../Frenck
