### ISSUE TITLE
Errors with Getting_Started.jpynp

### ISSUE THREAD

**Issue by derekPrivate** [hassio-addons/addon-jupyterlab#653]
# Problem/Motivation

The getting_started provided in the HomeAssistant add-on does not work, giving errors.

## Expected behavior

I don't expect errors in the provided notebook!

## Actual behavior
<img width="1012" alt="Screenshot 2024-12-06 at 20 28 09" src="https://github.com/user-attachments/assets/3678da61-9319-4d24-8009-8c57477c7dcf">

## Steps to reproduce

Install JupyterLab add-on to HomeAssistant. Open the getting_started.jpynb notebook and Run->All Cells, as instructed. This gives the following error (snapshot)

Operating System: HomeAssistant for Raspberry Pi
Core 2024.12.1
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.6
JupyterLabs Add-on 4.3.1

**Comment by frenck** [comment]
Hi there @derekPrivate 👋 

This getting started is not maintained by the add-on, but provided by the Home Assistant project. If this notebook isn't correct, please report it with that project.

The add-on will automatically update the getting started guide to the latest upstream version once the upstream has been fixed/adjusted.

Thanks 👍 

../Frenck
